# Generated by Django 4.0.4 on 2022-05-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default=0, max_length=50, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
