# Generated by Django 4.0.4 on 2022-05-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='calories',
            field=models.CharField(default=0, max_length=50, verbose_name='Калорийность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='width',
            field=models.CharField(default=0, max_length=50, verbose_name='Вес'),
            preserve_default=False,
        ),
    ]
