# Generated by Django 4.0.4 on 2022-05-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_calories_post_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=0, upload_to='category/', verbose_name='Миниатюра'),
            preserve_default=False,
        ),
    ]
